### ISSUE TITLE
The S2LP Everything Meta Issue

### ISSUE THREAD

**Issue by ryankurte** [rust-iot/rust-radio-s2lp#4]
At the moment this is basically a scaffold for a useful driver, to get this to a useful state we need to:

- [ ] Complete register descriptions (see [device.rs](https://github.com/rust-iot/rust-radio-s2lp/blob/master/src/device.rs))
  - The S2LP register map is _huge_, if you're interested, feel free to make partial contributions! 
- [ ] Implement radio configuration (see [lib.rs](https://github.com/rust-iot/rust-radio-s2lp/blob/master/src/lib.rs))
- [ ] Implement `radio::Channel`
- [ ] Implement `radio::State`
- [ ] Implement `radio::Transmit`
- [ ] Implement `radio::Receive`
- [ ] Build integration tests

Useful resources:

- [S2LP_Library](https://github.com/ryankurte/libsts2lp/tree/master/S2LP_Library)
- [datasheet](https://www.st.com/resource/en/datasheet/s2-lp.pdf)
